# Generated by managed-airflow-platform — copied to each deployment's config/ when compose is written.
#
# 1) FAB mounts a separate FastAPI app at /auth. Cross-origin fetch() to /auth/token is fragile (Safari "Load failed",
#    CORS, credentialed XHR). Handoff uses a top-level form POST to /auth/managed-platform-ui-handoff instead
#    (navigation — not subject to CORS).
# 2) POST /auth/token returns JSON only (no Set-Cookie). The Airflow 3 UI uses the _token cookie for /ui/.
#    The form handoff route sets that cookie on a 303 redirect; this middleware still helps JSON /auth/token clients.

import sys
import traceback


def _patch_fab_auth_handoff():
    from airflow.api_fastapi.app import get_cookie_path
    from airflow.api_fastapi.auth.managers.base_auth_manager import COOKIE_NAME_JWT_TOKEN
    from airflow.configuration import conf
    from airflow.providers.fab.auth_manager.fab_auth_manager import FabAuthManager
    from fastapi import Form, HTTPException, Request
    from fastapi.middleware.cors import CORSMiddleware
    from fastapi.responses import PlainTextResponse, RedirectResponse
    import json
    from starlette.middleware.base import BaseHTTPMiddleware
    from starlette.responses import JSONResponse, Response

    _orig_get_app = FabAuthManager.get_fastapi_app

    class _FabTokenCookieMiddleware(BaseHTTPMiddleware):
        """Mirror Simple-auth behavior: persist JWT as HttpOnly _token so /ui/ loads authenticated."""

        async def dispatch(self, request: Request, call_next):
            response = await call_next(request)
            path = request.url.path
            if request.method != "POST":
                return response
            if path.rstrip("/").endswith("/token/cli"):
                return response
            if not path.rstrip("/").endswith("/token"):
                return response
            if response.status_code != 201:
                return response

            body = b""
            async for chunk in response.body_iterator:
                body += chunk
            try:
                data = json.loads(body)
            except (json.JSONDecodeError, UnicodeDecodeError):
                return Response(
                    content=body,
                    status_code=response.status_code,
                    headers=dict(response.headers),
                )
            token = data.get("access_token")
            if not token or not isinstance(token, str):
                return Response(
                    content=body,
                    status_code=response.status_code,
                    headers=dict(response.headers),
                )

            secure = request.url.scheme == "https" or bool(conf.get("api", "ssl_cert", fallback=""))
            new_resp = JSONResponse(content=data, status_code=response.status_code)
            for k, v in response.headers.items():
                lk = k.lower()
                if lk not in ("content-length", "content-type", "set-cookie"):
                    new_resp.headers[k] = v
            new_resp.set_cookie(
                key=COOKIE_NAME_JWT_TOKEN,
                value=token,
                path=get_cookie_path(),
                httponly=True,
                secure=secure,
                samesite="lax",
            )
            return new_resp

    def _patched_get_fastapi_app(self):
        app = _orig_get_app(self)
        import os

        from airflow.providers.fab.auth_manager.api_fastapi.services.login import FABAuthManagerLogin
        from airflow.providers.fab.auth_manager.cli_commands.utils import get_application_builder

        def _managed_platform_ui_handoff(request: Request, username: str = Form(), password: str = Form()):
            """Same-origin (via top-level form POST) sign-in: avoids cross-origin fetch to /auth/token."""
            try:
                with get_application_builder():
                    lr = FABAuthManagerLogin.create_token(
                        headers=dict(request.headers),
                        body={"username": username, "password": password},
                    )
            except HTTPException as e:
                detail = e.detail
                if isinstance(detail, str):
                    msg = detail
                elif isinstance(detail, list):
                    msg = "; ".join(str(x) for x in detail)
                else:
                    msg = "Sign-in failed"
                return PlainTextResponse(msg, status_code=e.status_code)

            secure = request.url.scheme == "https" or bool(conf.get("api", "ssl_cert", fallback=""))
            # Must redirect to "/" not "/ui/": index.html sets <base href> from the request path; "/ui/" breaks
            # resolution of ./static assets (they live under /static, not /ui/static).
            resp = RedirectResponse(url="/", status_code=303)
            resp.set_cookie(
                key=COOKIE_NAME_JWT_TOKEN,
                value=lr.access_token,
                path=get_cookie_path(),
                httponly=True,
                secure=secure,
                samesite="lax",
            )
            return resp

        # FabAuthManager.get_fastapi_app ends with mount("/", WSGIMiddleware(flask_app)), which matches every path.
        # Routes registered after that mount are never reached. Insert this route *before* that Mount.
        from starlette.routing import Mount

        app.add_api_route(
            "/managed-platform-ui-handoff",
            _managed_platform_ui_handoff,
            methods=["POST"],
        )
        handoff_route = None
        for idx in range(len(app.router.routes) - 1, -1, -1):
            r = app.router.routes[idx]
            if getattr(r, "path", None) == "/managed-platform-ui-handoff":
                handoff_route = app.router.routes.pop(idx)
                break
        if handoff_route is None:
            print(
                "managed-airflow-platform: could not locate /managed-platform-ui-handoff route after add_api_route",
                file=sys.stderr,
            )
        else:
            insert_at = None
            for i, route in enumerate(app.router.routes):
                # FastAPI mount("/") is often stored as Mount with path "" (see Starlette); match both.
                if isinstance(route, Mount):
                    mp = getattr(route, "path", None)
                    if mp in ("/", "", None):
                        insert_at = i
                        break
            if insert_at is not None:
                app.router.routes.insert(insert_at, handoff_route)
            else:
                app.router.routes.append(handoff_route)
                print(
                    "managed-airflow-platform: could not find root Mount in FAB app; "
                    "managed-platform-ui-handoff may be unreachable",
                    file=sys.stderr,
                )

        raw = os.environ.get("AIRFLOW__API__ACCESS_CONTROL_ALLOW_ORIGINS", "")
        extra = [o for o in raw.replace(",", " ").split() if o]
        _LOCAL_ORIGIN_RE = r"^https?://(localhost|127\.0\.0\.1|\[::1\])(:[0-9]+)?$"
        # Inner: normalize /token response with Set-Cookie. Outer: CORS for browser handoff.
        app.add_middleware(_FabTokenCookieMiddleware)
        app.add_middleware(
            CORSMiddleware,
            allow_origins=extra,
            allow_origin_regex=_LOCAL_ORIGIN_RE,
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )
        return app

    FabAuthManager.get_fastapi_app = _patched_get_fastapi_app
    print(
        "managed-airflow-platform: patched FabAuthManager.get_fastapi_app "
        "(FAB /auth CORS, /auth/managed-platform-ui-handoff form handoff, /auth/token _token cookie)",
        file=sys.stderr,
    )


try:
    _patch_fab_auth_handoff()
except Exception:
    print("managed-airflow-platform: FAB auth handoff patch failed", file=sys.stderr)
    traceback.print_exc(file=sys.stderr)
